Switch to GDAL Alpine base image
The latest "testing" package on Alpine Edge started failing the build:
https://app.circleci.com/jobs/github/ministryofjustice/laa-legal-adviser-api/1379

```
  File "/usr/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/usr/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 49, in <module>
    lgdal = CDLL(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Error relocating /usr/lib/libgdal.so.20: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

I briefly tried to compile from source but that turned out to be quite a
big timesink.

Afterwards, I noticed that GDAL has official Docker builds and they do
support Alpine Linux.

The tradeoff is that they seem to have built against Alpine 3.9, which
is one version backwards.

It seems to work though and it will still deliver build time speedups.