Upgrade psycopg2
To get around the need to install pre-PostgreSQL 10.x client locally, as
`psycopg 2.6` fails with:

    Error: could not determine PostgreSQL version from '10.2'