Skip seeding when adviser data already exists
As seeding is currently auto-enabled on every environment apart from
production (in `docker/run.sh`), we may run into issues when the
database has already been used before:

```
8000...
Traceback (most recent call last):
<snip>
django.db.utils.IntegrityError: duplicate key value violates unique constraint "advisers_office_account_number_key"
DETAIL:  Key (account_number)=(2M332T) already exists.
```

To avoid this this commit introduces a check to see if locations are
empty before attempting to seed.